services:
  db:
    image: mysql:8.2
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: lojavirtual
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
#      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
