spring.application.name=lojavirtual

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/lojavirtual?serverTimezone=UTC}
spring.datasource.username=${MYSQL_USERNAME:admin}
spring.datasource.password=${MYSQL_PASSWORD:admin}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

jwt.secret=${JWT_SECRET:chave-secreta-loja-virtual-jwt-256-bits-segura-2024}
jwt.expiration=${JWT_EXPIRATION:600000}
